apiVersion: v1
kind: Service
metadata:
  name: 2nd-service
  namespace: first-bank
spec:
  selector:
    app: 2nd-label
  ports:
  - port: 33000
    protocol: TCP
    targetPort: 32000






