
apiVersion: v1
kind: Service
metadata:
  name: 2nd-service
spec:
  type: NodePort
  selector:
    app: 2nd-label
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
      protocol: TCP
      

