apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  


# apiVersion: v1
# kind: Service
# metadata:
#   name: argocd-server
# spec:
#   type: NodePort
#   selector:
#     app.kubernetes.io/name: argocd-server
#   ports:
#     - name: http
#       port: 80
#       targetPort: 8080
#       protocol: TCP
#     - name: https
#       port: 443
#       targetPort: 8080
#       protocol: TCP
