apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  namespace: vic
  labels:
    app: frontend
spec:
  containers:
  - name: redis-container
    image: redis:latest
    ports:
    - containerPort: 6379
