apiVersion: v1
kind: Pod
metadata:
  name: new-pod
  namespace: jay
spec:
 containers:
 - name: simple-webapp-color
   image: nginx
   ports:
   - containerPort: 80 
   
   envFrom:      #used to load all key pair values as environmental variables of CM or secretes into pod
   - configMapRef:
       name: app-config


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: jay
data:
  APP_COLOR: blue
  APP_MODE: prod
