kind: Cluster

apiVersion: kind.x-k8s.io/v1alpha4

# name: vic-cluster

nodes:

- role: control-plane

- role: worker

- role: worker

- role: worker

- role: worker

# networking: 
#   disableDefaultCNI: true
#   podSubnet: 192.168.0.0/16

# kind delete cluster -n=kube-monitor ----> this is a way to remove the cluster 
# kind create cluster --name=vic-cluster --config=new-cluster.yaml