apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: vic
  labels:
    app: webserver
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14.2
    ports:
    - containerPort: 80


---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: vic
  labels:
    app: webserver-2
spec:
  containers:
  - name: nginx-4
    image: ubuntu:latest
    ports:
    - containerPort: 80