apiVersion: v1
kind: ServiceAccount   # this is not a Service but k8s api object
metadata:
  name: pod-reader-sa
  namespace: jay
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: jay
subjects:
- kind: ServiceAccount
  name: pod-reader-sa
  namespace: jay
roleRef:
  kind: Role
  name: pod-reader-role
  apiGroup: rbac.authorization.k8s.io 